version: '3.3'

services:
  db:
    image: mysql:8.0.15
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: schakry
      MYSQL_USER: playboy
      MYSQL_PASSWORD: chakry123456789

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: playboy
      WORDPRESS_DB_PASSWORD: chakry123456789
      WORDPRESS_DB_NAME: chakry
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
